import type { Certification } from '../types';

export const CERTIFICATIONS: readonly Certification[] = [
  {
    id: 'aws-saa',
    nameKey: 'home.certs.aws-saa.name',
    issuerKey: 'home.certs.aws-saa.issuer',
    issued: 'Jun 2026',
    expires: 'Jun 2029',
    credentialId: '5fa348b1-de2c-4884-957e-ae21e7515b56',
    skills: ['Cloud Architecture', 'AWS', 'High Availability', 'Cost Optimization'],
    logo: '/icons/aws-wordmark.svg',
    descKey: 'home.certs.aws-saa.desc',
  },
  {
    id: 'hccdp',
    nameKey: 'home.certs.hccdp.name',
    issuerKey: 'home.certs.hccdp.issuer',
    division: 'HUAWEI CLOUD',
    issued: 'Jun 2026',
    expires: 'Jun 2029',
    credentialId: 'HWENDCCCDP00180959183',
    skills: ['Cloud Architecture', 'Huawei Cloud', 'Distributed Systems', 'Cost Optimization'],
    logo: '/icons/huawei.svg',
    descKey: 'home.certs.hccdp.desc',
  },
  {
    id: 'hccda',
    nameKey: 'home.certs.hccda.name',
    issuerKey: 'home.certs.hccda.issuer',
    division: 'HUAWEI CLOUD',
    issued: 'May 2026',
    expires: 'May 2029',
    credentialId: 'HWENDCTEDA542672',
    skills: ['Cloud Architecture', 'Huawei Cloud', 'Cloud Foundations'],
    logo: '/icons/huawei.svg',
    descKey: 'home.certs.hccda.desc',
  },
  {
    id: 'aws-ccp',
    nameKey: 'home.certs.aws-ccp.name',
    issuerKey: 'home.certs.aws-ccp.issuer',
    issued: 'Apr 2026',
    expires: 'Apr 2029',
    credentialId: '72b404c5-b893-47a9-a8dc-688a9337ce57',
    skills: ['Cloud Computing', 'Cloud Services', 'AWS Foundations'],
    logo: '/icons/aws-wordmark.svg',
    descKey: 'home.certs.aws-ccp.desc',
  },
  {
    id: 'hcia-ai',
    nameKey: 'home.certs.hcia-ai.name',
    issuerKey: 'home.certs.hcia-ai.issuer',
    issued: 'Aug 2020',
    expires: 'Aug 2023',
    credentialId: '01010200180804649576366',
    skills: ['Python', 'Artificial Intelligence', 'Machine Learning', 'Deep Learning'],
    logo: '/icons/huawei.svg',
    descKey: 'home.certs.hcia-ai.desc',
  },
] as const satisfies readonly Certification[];
