import type { Certification } from '../types';

export const CERTIFICATIONS: readonly Certification[] = [
  {
    id: 'aws-saa',
    nameKey: 'home.certs.aws-saa.name',
    issuerKey: 'home.certs.aws-saa.issuer',
    issued: 'Jun 2026',
    expires: 'Jun 2029',
    credentialId: '5fa348b1-de2c-4884-957e-ae21e7515b56',
    verifyUrl: 'https://www.credly.com/badges/5fa348b1-de2c-4884-957e-ae21e7515b56/public_url',
    skills: ['VPC & IAM', 'EC2 / Lambda', 'RDS / DynamoDB', 'Multi-AZ HA/DR'],
    logo: '/icons/aws-wordmark.svg',
    descKey: 'home.certs.aws-saa.desc',
  },
  {
    id: 'hccdp',
    nameKey: 'home.certs.hccdp.name',
    issuerKey: 'home.certs.hccdp.issuer',
    division: 'HUAWEI CLOUD',
    issued: 'Jun 2026',
    expires: 'Jun 2029',
    credentialId: 'HWENDCCCDP00180959183',
    verifyUrl: 'https://drive.google.com/file/d/1aJL8bRgC8p_lp8HcLkV4GxkNkxDjXQW3/view',
    skills: ['ECS & OBS', 'VPC / ELB', 'Managed Databases', 'HA & Cost'],
    logo: '/icons/huawei.svg',
    descKey: 'home.certs.hccdp.desc',
  },
  {
    id: 'aws-ccp',
    nameKey: 'home.certs.aws-ccp.name',
    issuerKey: 'home.certs.aws-ccp.issuer',
    issued: 'Apr 2026',
    expires: 'Apr 2029',
    credentialId: '72b404c5-b893-47a9-a8dc-688a9337ce57',
    verifyUrl: 'https://www.credly.com/badges/9bf189ec-3eb3-415b-b20a-67750205c915/public_url',
    skills: ['Cloud Concepts', 'Shared Responsibility', 'Pricing & Billing', 'Core Services'],
    logo: '/icons/aws-wordmark.svg',
    descKey: 'home.certs.aws-ccp.desc',
  },
  {
    id: 'hccda',
    nameKey: 'home.certs.hccda.name',
    issuerKey: 'home.certs.hccda.issuer',
    division: 'HUAWEI CLOUD',
    issued: 'May 2026',
    expires: 'May 2029',
    credentialId: 'HWENDCTEDA542672',
    verifyUrl: 'https://drive.google.com/file/d/1auStEZzvooP8LXHBIpv_T4VwS0C-AV5X/view',
    skills: ['Core Compute', 'Storage & Networking', 'App Deployment'],
    logo: '/icons/huawei.svg',
    descKey: 'home.certs.hccda.desc',
  },
] as const satisfies readonly Certification[];
