import type { WorkProject } from '../types';

// Product names, screenshots, and live links are published deliberately (restored
// 2026-09-19). The copy itself stays team-framed and cites only numbers the
// Experience section corroborates — next-intl serialises the whole message
// dictionary into the prerendered HTML, so anything under `home.work.*` ships even
// if a card is hidden. Both rules are enforced by __tests__/config/work.policy.test.ts.
//
// Ordering: newest year first; within a year, the largest-scope contribution first.
export const WORK: readonly WorkProject[] = [
  {
    id: 'miite',
    kind: 'live',
    url: 'https://awards.miite.ae/en',
    image: '/work/miite.webp',
    nameKey: 'home.work.miite.name',
    companyKey: 'home.work.miite.company',
    periodKey: 'home.work.miite.period',
    blurbKey: 'home.work.miite.blurb',
    highlights: [
      { value: '5,000+', labelKey: 'home.work.highlight.users' },
      { value: '−35%', labelKey: 'home.work.highlight.latency' },
      { value: '<5 min', labelKey: 'home.work.highlight.deployTime' },
    ],
    stack: [
      'Next.js',
      'NestJS',
      'PostgreSQL',
      'Prisma ORM',
      'AWS (VPC, EC2, RDS, S3, CloudFront, IAM, Secrets Manager, ECR, ECS, CodeBuild, CodePipeline, CloudWatch)',
      'Docker',
      'TypeScript',
      'React',
      'Vitest',
      'React Testing Library',
      'Playwright',
    ],
    swatch: ['#1a1410', '#3a2a18', '#d4a574'],
    badgeKey: 'home.work.miite.badge',
    caseStudy: {
      roleKey: 'home.work.miite.caseStudy.role',
      overviewKey: 'home.work.miite.caseStudy.overview',
      systemKey: 'home.work.miite.caseStudy.system',
      contributionsKey: 'home.work.miite.caseStudy.contributions',
    },
  },
  {
    id: 'lawmate',
    kind: 'private',
    image: '/work/lawmate.webp',
    nameKey: 'home.work.lawmate.name',
    companyKey: 'home.work.lawmate.company',
    periodKey: 'home.work.lawmate.period',
    blurbKey: 'home.work.lawmate.blurb',
    highlights: [
      { value: 'Laravel', labelKey: 'home.work.highlight.apiFirst' },
      { value: 'Paymob', labelKey: 'home.work.highlight.wallet' },
      { value: 'EN/AR', labelKey: 'home.work.highlight.bilingual' },
    ],
    // The row shows the first six chips, so lead with what the blurb sells.
    stack: [
      'Laravel',
      'MySQL',
      'Redis',
      'WebSockets (Laravel Reverb)',
      'Paymob',
      'Filament (Livewire)',
      'PHP',
      'Sanctum',
      'Twilio',
      'AWS S3',
      'Firebase Cloud Messaging',
      'Pest',
      'PHPUnit',
    ],
    swatch: ['#17100e', '#2e1d18', '#c8996a'],
    badgeKey: 'home.work.lawmate.badge',
    caseStudy: {
      roleKey: 'home.work.lawmate.caseStudy.role',
      overviewKey: 'home.work.lawmate.caseStudy.overview',
      systemKey: 'home.work.lawmate.caseStudy.system',
      contributionsKey: 'home.work.lawmate.caseStudy.contributions',
    },
  },
  {
    id: 'sabeel',
    kind: 'private',
    image: '/work/sabeel.webp',
    nameKey: 'home.work.sabeel.name',
    companyKey: 'home.work.sabeel.company',
    periodKey: 'home.work.sabeel.period',
    blurbKey: 'home.work.sabeel.blurb',
    highlights: [
      { value: 'Laravel', labelKey: 'home.work.highlight.restApi' },
      { value: 'MySQL', labelKey: 'home.work.highlight.rds' },
      { value: 'CloudWatch', labelKey: 'home.work.highlight.monitoring' },
    ],
    stack: [
      'Laravel',
      'PHP',
      'MySQL',
      'AWS (ECS, ECR, RDS, ALB, VPC, S3, CloudFront, IAM, Secrets Manager, CodeBuild, CodePipeline, CloudWatch)',
      'Docker',
      'CI/CD',
    ],
    swatch: ['#11171a', '#1c2a32', '#7ea7b8'],
    badgeKey: 'home.work.sabeel.badge',
    caseStudy: {
      roleKey: 'home.work.sabeel.caseStudy.role',
      overviewKey: 'home.work.sabeel.caseStudy.overview',
      systemKey: 'home.work.sabeel.caseStudy.system',
      contributionsKey: 'home.work.sabeel.caseStudy.contributions',
    },
  },
  {
    id: 'altanfeethi',
    kind: 'private',
    image: '/work/altanfeethi.webp',
    nameKey: 'home.work.altanfeethi.name',
    companyKey: 'home.work.altanfeethi.company',
    periodKey: 'home.work.altanfeethi.period',
    blurbKey: 'home.work.altanfeethi.blurb',
    highlights: [
      { value: 'APIM', labelKey: 'home.work.highlight.gateway' },
      { value: 'Azure', labelKey: 'home.work.highlight.provisioning' },
      { value: 'CI/CD', labelKey: 'home.work.highlight.pipelines' },
    ],
    stack: ['Microsoft Azure', 'Azure API Management', 'Azure DevOps', 'CI/CD'],
    swatch: ['#0f1116', '#1a1d2a', '#c1b5d6'],
    badgeKey: 'home.work.altanfeethi.badge',
    caseStudy: {
      roleKey: 'home.work.altanfeethi.caseStudy.role',
      overviewKey: 'home.work.altanfeethi.caseStudy.overview',
      systemKey: 'home.work.altanfeethi.caseStudy.system',
      contributionsKey: 'home.work.altanfeethi.caseStudy.contributions',
    },
  },
  {
    id: 'esl',
    kind: 'live',
    url: 'https://esl.moe.gov.eg/ar',
    image: '/work/esl.webp',
    nameKey: 'home.work.esl.name',
    companyKey: 'home.work.esl.company',
    periodKey: 'home.work.esl.period',
    blurbKey: 'home.work.esl.blurb',
    highlights: [
      { value: 'NestJS', labelKey: 'home.work.highlight.rulesEngine' },
      { value: 'WebSockets', labelKey: 'home.work.highlight.leaderboards' },
      { value: 'Prisma', labelKey: 'home.work.highlight.dataLayer' },
    ],
    stack: [
      'Next.js',
      'NestJS',
      'PostgreSQL',
      'Prisma ORM',
      'WebSockets',
      'Docker',
      'React',
      'TypeScript',
    ],
    swatch: ['#10130f', '#1c2a1a', '#a8c190'],
    badgeKey: 'home.work.esl.badge',
    caseStudy: {
      roleKey: 'home.work.esl.caseStudy.role',
      overviewKey: 'home.work.esl.caseStudy.overview',
      systemKey: 'home.work.esl.caseStudy.system',
      contributionsKey: 'home.work.esl.caseStudy.contributions',
    },
  },
  {
    id: 'whatsapp-bot',
    kind: 'private',
    image: '/work/whatsapp-bot.webp',
    nameKey: 'home.work.whatsappBot.name',
    companyKey: 'home.work.whatsappBot.company',
    periodKey: 'home.work.whatsappBot.period',
    blurbKey: 'home.work.whatsappBot.blurb',
    highlights: [
      { value: 'Lex', labelKey: 'home.work.highlight.intents' },
      { value: 'Lambda', labelKey: 'home.work.highlight.orchestration' },
      { value: 'Twilio', labelKey: 'home.work.highlight.channel' },
    ],
    stack: [
      'Python',
      'AWS Lambda',
      'Amazon Lex',
      'Twilio API',
      'AWS Secrets Manager',
      'Amazon CloudWatch',
    ],
    swatch: ['#0f1316', '#1a2330', '#88a6d4'],
    badgeKey: 'home.work.whatsappBot.badge',
    caseStudy: {
      roleKey: 'home.work.whatsappBot.caseStudy.role',
      overviewKey: 'home.work.whatsappBot.caseStudy.overview',
      systemKey: 'home.work.whatsappBot.caseStudy.system',
      contributionsKey: 'home.work.whatsappBot.caseStudy.contributions',
    },
  },
] as const satisfies readonly WorkProject[];
