import type { WorkProject } from '../types';

export const WORK: readonly WorkProject[] = [
  {
    id: 'mie',
    nameKey: 'home.work.mie.name',
    companyKey: 'home.work.mie.company',
    periodKey: 'home.work.mie.period',
    blurbKey: 'home.work.mie.blurb',
    metrics: [
      { value: '5,000+', labelKey: 'home.work.metric.users' },
      { value: '−35%', labelKey: 'home.work.metric.latency' },
      { value: '4×', labelKey: 'home.work.metric.deploys' },
    ],
    stack: [
      'Next.js',
      'NestJS',
      'PostgreSQL',
      'Prisma',
      'AWS (VPC, EC2, RDS, S3, CloudFront, IAM, Secrets Manager, ECR, ECS, CodeBuild, CodePipeline)',
      'Docker',
      'Vitest',
      'Playwright',
    ],
    image: '/work/miite.webp',
    swatch: ['#1a1410', '#3a2a18', '#d4a574'],
    kind: 'live',
    url: 'https://awards.miite.ae/en',
    badgeKey: 'home.work.mie.badge',
    caseStudy: {
      roleKey: 'home.work.mie.caseStudy.role',
      problemKey: 'home.work.mie.caseStudy.problem',
      architectureKey: 'home.work.mie.caseStudy.architecture',
      contributionsKey: 'home.work.mie.caseStudy.contributions',
    },
  },
  {
    id: 'lawmate',
    nameKey: 'home.work.lawmate.name',
    companyKey: 'home.work.lawmate.company',
    periodKey: 'home.work.lawmate.period',
    blurbKey: 'home.work.lawmate.blurb',
    metrics: [
      { value: 'API-first', labelKey: 'home.work.metric.backend' },
      { value: 'Paymob', labelKey: 'home.work.metric.wallet' },
      { value: 'EN/AR', labelKey: 'home.work.metric.bilingual' },
    ],
    stack: [
      'Laravel',
      'PHP',
      'MySQL',
      'Redis',
      'Filament (Livewire)',
      'Sanctum',
      'Reverb (WebSockets)',
      'Twilio',
      'Paymob',
      'AWS S3',
      'FCM',
      'Pest',
      'PHPUnit',
    ],
    image: '/work/lawmate.webp',
    swatch: ['#17100e', '#2e1d18', '#c8996a'],
    kind: 'private',
    badgeKey: 'home.work.lawmate.badge',
    caseStudy: {
      roleKey: 'home.work.lawmate.caseStudy.role',
      problemKey: 'home.work.lawmate.caseStudy.problem',
      architectureKey: 'home.work.lawmate.caseStudy.architecture',
      contributionsKey: 'home.work.lawmate.caseStudy.contributions',
    },
  },
  {
    id: 'sabeel',
    nameKey: 'home.work.sabeel.name',
    companyKey: 'home.work.sabeel.company',
    periodKey: 'home.work.sabeel.period',
    blurbKey: 'home.work.sabeel.blurb',
    metrics: [
      { value: 'lower', labelKey: 'home.work.metric.latency' },
      { value: 'k‑scale', labelKey: 'home.work.metric.active' },
      { value: 'AWS', labelKey: 'home.work.metric.prodinfra' },
    ],
    stack: [
      'Laravel',
      'PHP',
      'MySQL',
      'AWS (ECS, ECR, RDS, VPC, ALB, S3, CloudFront, IAM, Secrets Manager, CodeBuild, CodePipeline, CloudWatch)',
      'CI/CD',
    ],
    image: '/work/sabeel.webp',
    swatch: ['#11171a', '#1c2a32', '#7ea7b8'],
    kind: 'private',
    badgeKey: 'home.work.sabeel.badge',
    caseStudy: {
      roleKey: 'home.work.sabeel.caseStudy.role',
      problemKey: 'home.work.sabeel.caseStudy.problem',
      architectureKey: 'home.work.sabeel.caseStudy.architecture',
      contributionsKey: 'home.work.sabeel.caseStudy.contributions',
    },
  },
  {
    id: 'esl',
    nameKey: 'home.work.esl.name',
    companyKey: 'home.work.esl.company',
    periodKey: 'home.work.esl.period',
    blurbKey: 'home.work.esl.blurb',
    metrics: [
      { value: 'zero', labelKey: 'home.work.metric.admin' },
      { value: 'auto', labelKey: 'home.work.metric.efficiency' },
      { value: 'realtime', labelKey: 'home.work.metric.leaderboards' },
    ],
    stack: ['Next.js', 'React', 'TypeScript', 'NestJS', 'PostgreSQL', 'Prisma', 'Docker'],
    image: '/work/esl.webp',
    swatch: ['#10130f', '#1c2a1a', '#a8c190'],
    kind: 'live',
    url: 'https://esl.moe.gov.eg/ar',
    badgeKey: 'home.work.esl.badge',
    caseStudy: {
      roleKey: 'home.work.esl.caseStudy.role',
      problemKey: 'home.work.esl.caseStudy.problem',
      architectureKey: 'home.work.esl.caseStudy.architecture',
      contributionsKey: 'home.work.esl.caseStudy.contributions',
    },
  },
  {
    id: 'wabot',
    nameKey: 'home.work.wabot.name',
    companyKey: 'home.work.wabot.company',
    periodKey: 'home.work.wabot.period',
    blurbKey: 'home.work.wabot.blurb',
    metrics: [
      { value: 'zero', labelKey: 'home.work.metric.automated' },
      { value: 'serverless', labelKey: 'home.work.metric.coldstart' },
      { value: 'event', labelKey: 'home.work.metric.eventarch' },
    ],
    stack: [
      'Python',
      'AWS Lambda',
      'Amazon Lex',
      'Twilio API',
      'AWS Secrets Manager',
      'CloudWatch',
    ],
    image: '/work/whatsapp-bot.webp',
    swatch: ['#0f1316', '#1a2330', '#88a6d4'],
    kind: 'private',
    badgeKey: 'home.work.wabot.badge',
    caseStudy: {
      roleKey: 'home.work.wabot.caseStudy.role',
      problemKey: 'home.work.wabot.caseStudy.problem',
      architectureKey: 'home.work.wabot.caseStudy.architecture',
      contributionsKey: 'home.work.wabot.caseStudy.contributions',
    },
  },
  {
    id: 'eltan',
    nameKey: 'home.work.eltan.name',
    companyKey: 'home.work.eltan.company',
    periodKey: 'home.work.eltan.period',
    blurbKey: 'home.work.eltan.blurb',
    metrics: [
      { value: 'Azure', labelKey: 'home.work.metric.infra' },
      { value: 'CI/CD', labelKey: 'home.work.metric.pipelines' },
      { value: 'prod', labelKey: 'home.work.metric.shipped' },
    ],
    stack: ['Microsoft Azure', 'Azure API Management', 'CI/CD'],
    image: '/work/eltanfeethi.webp',
    swatch: ['#0f1116', '#1a1d2a', '#c1b5d6'],
    kind: 'private',
    badgeKey: 'home.work.eltan.badge',
    caseStudy: {
      roleKey: 'home.work.eltan.caseStudy.role',
      problemKey: 'home.work.eltan.caseStudy.problem',
      architectureKey: 'home.work.eltan.caseStudy.architecture',
      contributionsKey: 'home.work.eltan.caseStudy.contributions',
    },
  },
] as const satisfies readonly WorkProject[];
